### ISSUE TITLE
Support for ELSI

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/dftbplus-feedstock#15]
ELSI is now available on conda-forge (https://github.com/conda-forge/elsi-feedstock), we can already make use of it for Linux/x86_64 and MacOS/x86_64. ~~Linux/aarch64 and Linux/ppc64le migrations are underway, but probably stuck a while at the ELPA feedstock ;).~~

Should we build the MPI version by default with ELSI support?

**Comment by bhourahine** [comment]
@awvwgk the download [stats](https://anaconda.org/conda-forge/dftbplus/files) suggest these are both about 5% of the Linux downloads (which is about x2 the MacOS). I guess having "with" and "without" versions is too much of a combinatorial mess.

**Comment by awvwgk** [comment]
ELSI is reexporting symbols of its dependencies but doesn't export the required link dependencies, therefore we can't use ELSI yet. I opened an issue upstream (https://gitlab.com/elsi_project/elsi_interface/-/issues/57) to find a solution.
