### ISSUE TITLE
Support Python API

### ISSUE THREAD

**Issue by njzjz** [conda-forge/dftbplus-feedstock#33]
### Comment:

Currently, this conda package does not contain Python API.

https://github.com/dftbplus/dftbplus/blob/main/tools/pythonapi/src/dftbplus.py

**Comment by awvwgk** [comment]
There is a separate feedstock called https://github.com/conda-forge/dftbplus-python-feedstock for this.

**Comment by njzjz** [comment]
Got it. Thanks!
